apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: j2c-route
spec:
  host: app7.app.ns-test.cloudlab.j2ctechnologie.intern
  to:
    kind: Service
    name: j2c_app
  port:
    targetPort: 8080-9001
