apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: j2c-route
spec:
  host: app2.app.nstest.cloud-lab.j2ctechnologies.intern
  to:
    kind: Service
    name: j2c_app
  port:
    targetPort: 8080-9001
